name: CI

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    
    - name: Checkout
      uses: actions/checkout@v2

    - name: Build
      run: |
        npm install
        npm run build
      env:
        VITE_SUPABASE_ANON_KEY: ${{ secrets.KEY }}
        VITE_SUPABASE_URL: ${{ secrets.URL }}

    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages
        FOLDER: dist
